function orgt(s) {
  return binl2hex(core_hx(str2binl(s), s.length * chrsz))
}
var bookConfig = {
  DownloadButtonVisible: 'Hide',
  BookmarkButtonVisible: 'Show',
  searchColor: '#00ffff',
  searchAlpha: 0.3,
  leastSearchChar: 0,
  CreatedBy: 'Flip HTML5 for windows 6.6.2.0',
  CreatedTime: '20220427161232',
  BookTemplateName: 'Popular',
  loadingBackground: '#323232',
  searchPositionJS: 'files/search/text_position[%d].js',
  loadingCaption: '',
  loadingCaptionFontSize: 20,
  loadingCaptionColor: '#DDDDDD',
  loadingBackground: '#323232',
  loadingPicture: '',
  loadingPictureHeight: 150,
  showLoadingGif: 'Yes',
  loadingDisplayTime: 0,
  loadingVideo: '',
  bgBeginColor: '#EFEFEF',
  bgEndColor: '#808DAE',
  bgMRotation: 90,
  backGroundImgURL: '',
  backgroundPosition: 'Fill',
  backgroundOpacity: 100,
  backgroundScene: 'None',
  LeftShadowWidth: 100,
  LeftShadowAlpha: 1,
  RightShadowWidth: 40,
  RightShadowAlpha: 1,
  ShowTopLeftShadow: 'Yes',
  FlipStyle: 'Flip',
  FlipDirection: '0',
  autoDoublePage: 'Auto',
  showMirrorSide: 'Show',
  SingleModeBanFlipToLastPage: 'No',
  retainBookCenter: 'Yes',
  isTheBookOpen: 'No',
  RightToLeft: 'No',
  pageBackgroundColor: '#FFFFFF',
  pageHighlightType: 'magazine',
  OriginPageIndex: 1,
  QRCode: 'Hide',
  thicknessWidthType: 'thick',
  thicknessColor: '#FFFFFF',
  showThicknessOnMobile: 'No',
  BindingType: 'side',
  HardPageEnable: 'No',
  hardCoverBorderWidth: 8,
  cornerRound: 8,
  borderColor: '#572F0D',
  outerCoverBorder: 'Yes',
  coverTexture: 'none',
  HardInnerPageEnable: 'No',
  highDefinitionConversion: 'No',
  isSingleBookFullWindowOnMobile: 'No',
  totalPagesCaption: '',
  pageNumberCaption: '',
  leftMargin: 10,
  topMargin: 10,
  rightMargin: 10,
  bottomMargin: 10,
  leftMarginOnMobile: 0,
  topMarginOnMobile: 0,
  rightMarginOnMobile: 0,
  bottomMarginOnMobile: 0,
  bleedAreaLeft: '0%',
  bleedAreaTop: '0%',
  bleedAreaRight: '0%',
  bleedAreaBottom: '0%',
  maxWidthToSmallMode: '400',
  maxHeightToSmallMode: '300',
  ToolBarVisible: 'Yes',
  toolbarAlwaysShow: 'No',
  ToolBarAlpha: 1,
  toolbarColor: '#111111',
  iconColor: '#EEEEEE',
  iconFontColor: '#EEEEEE',
  pageNumColor: '#111111',
  formBackgroundColor: '#111111',
  formFontColor: '#EEEEEE',
  flipshortcutbutton: 'Show',
  phoneFlipShortcutButton: 'Hide',
  leftRightPnlShowOption: 'none',
  appLogoIcon: 'files/extfile/logo_back.png',
  appLogoLinkURL: 'http://yx.whisper.ink',
  appLogoOpenWindow: 'Blank',
  logoHeight: 25,
  logoPadding: 10,
  FirstButtonIcon: '',
  PreviousButtonIcon: '',
  NextButtonIcon: '',
  LastButtonIcon: '',
  showGotoButtonsAtFirst: 'No',
  enablePageBack: 'Hide',
  BackwardButtonIcon: '',
  ForwardButtonIcon: '',
  HomeButtonVisible: 'Hide',
  HomeURL: '%first page%',
  HomeButtonIcon: '',
  AnnotationButtonVisible: 'Hide',
  AnnotationButtonIcon: '',
  ShareButtonVisible: 'Show',
  ShareButtonIcon: '',
  addCurrentPage: 'Hide',
  isInsertFrameLinkEnable: 'Show',
  facebookShotImageURL: '',
  facebookAppId: '',
  ThumbnailsButtonVisible: 'Show',
  ThumbnailButtonIcon: '',
  ZoomButtonVisible: 'Show',
  SupportOperatePageZoom: 'Yes',
  ZoomToolbarVisible: 'Show',
  ZoomMapVisible: 'Hide',
  ZoomInButtonIcon: '',
  ZoomOutButtonIcon: '',
  MagnifierButtonVisible: 'Hide',
  FullscreenButtonVisible: 'Show',
  FullscreenButtonIcon: '',
  ExitFullscreenButtonIcon: '',
  hideMiniFullscreen: 'No',
  BookMarkButtonVisible: 'Hide',
  BookmarkButtonIcon: '',
  TableOfContentButtonVisible: 'Hide',
  isHideTabelOfContentNodes: 'Yes',
  TableOfContentButtonIcon: '',
  SearchButtonVisible: 'Show',
  leastSearchChar: 3,
  searchKeywordFontColor: '#FFB000',
  searchHightlightColor: '#FDC606',
  SearchButtonIcon: '',
  SelectTextButtonVisible: 'Show',
  SelectTextButtonIcon: '',
  PrintButtonVisible: 'Show',
  PrintButtonIcon: '',
  printWatermarkFile: '',
  FlipSound: 'Yes',
  BackgroundSoundButtonVisible: 'Hide',
  BackgroundSoundURL: '',
  bgSoundVol: 50,
  BackgroundSoundLoop: -1,
  BackgroundSoundButtonOnIcon: '',
  BackgroundSoundButtonOffIcon: '',
  HelpButtonVisible: 'Hide',
  helpContentFileURL: '',
  helpWidth: 400,
  helpHeight: 450,
  showHelpContentAtFirst: 'No',
  HelpButtonIcon: '',
  InstructionsButtonVisible: 'Show',
  showBookInstructionOnStart: 'No',
  showInstructionOnStart: 'Yes',
  aboutButtonVisible: 'Show',
  CompanyLogoFile: '',
  AboutButtonIcon: '',
  AutoPlayButtonVisible: 'Show',
  autoPlayAutoStart: 'No',
  autoPlayDuration: 3,
  autoPlayLoopCount: 1,
  AutoPlayStartButtonIcon: '',
  AutoPlayStopButtonIcon: '',
  minZoomWidth: 403,
  minZoomHeight: 518,
  DownloadButtonVisible: 'Hide',
  DownloadButtonIcon: '',
  DownloadURL: '',
  VideoButtonVisible: 'Hide',
  VideoButtonIcon: '',
  SlideshowButtonVisible: 'Hide',
  SlideshowButtonIcon: '',
  PhoneButtonVisible: 'Hide',
  PhoneButtonIcon: '',
  flippingTime: 0.6,
  mouseWheelFlip: 'Yes',
  CurlingPageCorner: 'Yes',
  updateURLForPage: 'Yes',
  updatePageNumberForFlip: 'No',
  isStopMouseMenu: 'Yes',
  OnlyOpenInIframe: 'No',
  OnlyOpenInIframeInfo: 'No reading rights',
  haveAdSense: 'No',
  adSenseWidth: 200,
  adSenseHeight: 200,
  adSenseLeft: 50,
  adSenseTop: 50,
  adSenseClientId: '',
  googleAnalyticsID: '',
  language: 'Chinese',
  AboutAddress: '湖南工业大学印刷1903班',
  AboutEmail: '273266469@qq.com',
  AboutMobile: '13*********2',
  AboutWebsite: 'http://yx.whisper.ink',
  AboutDescription: '',
  AboutAuthor: 'Vangogh',
  SlideshowAutoPlay: false,
  SlideshowPlayInterval: 5,
  totalPageCount: 100,
  largePageWidth: 2480,
  largePageHeight: 3366,
  normalPath: 'files/page/',
  largePath: 'files/large/',
  thumbPath: 'files/thumb/',
}
var fliphtml5_pages = [
  { l: 'files/page/1.jpg', n: 'files/page/1.jpg', t: 'files/thumb/1.jpg' },
  { l: 'files/page/2.jpg', n: 'files/page/2.jpg', t: 'files/thumb/2.jpg' },
  { l: 'files/page/3.jpg', n: 'files/page/3.jpg', t: 'files/thumb/3.jpg' },
  { l: 'files/page/4.jpg', n: 'files/page/4.jpg', t: 'files/thumb/4.jpg' },
  { l: 'files/page/5.jpg', n: 'files/page/5.jpg', t: 'files/thumb/5.jpg' },
  { l: 'files/page/6.jpg', n: 'files/page/6.jpg', t: 'files/thumb/6.jpg' },
  { l: 'files/page/7.jpg', n: 'files/page/7.jpg', t: 'files/thumb/7.jpg' },
  { l: 'files/page/8.jpg', n: 'files/page/8.jpg', t: 'files/thumb/8.jpg' },
  { l: 'files/page/9.jpg', n: 'files/page/9.jpg', t: 'files/thumb/9.jpg' },
  { l: 'files/page/10.jpg', n: 'files/page/10.jpg', t: 'files/thumb/10.jpg' },
  { l: 'files/page/11.jpg', n: 'files/page/11.jpg', t: 'files/thumb/11.jpg' },
  { l: 'files/page/12.jpg', n: 'files/page/12.jpg', t: 'files/thumb/12.jpg' },
  { l: 'files/page/13.jpg', n: 'files/page/13.jpg', t: 'files/thumb/13.jpg' },
  { l: 'files/page/14.jpg', n: 'files/page/14.jpg', t: 'files/thumb/14.jpg' },
  { l: 'files/page/15.jpg', n: 'files/page/15.jpg', t: 'files/thumb/15.jpg' },
  { l: 'files/page/16.jpg', n: 'files/page/16.jpg', t: 'files/thumb/16.jpg' },
  { l: 'files/page/17.jpg', n: 'files/page/17.jpg', t: 'files/thumb/17.jpg' },
  { l: 'files/page/18.jpg', n: 'files/page/18.jpg', t: 'files/thumb/18.jpg' },
  { l: 'files/page/19.jpg', n: 'files/page/19.jpg', t: 'files/thumb/19.jpg' },
  { l: 'files/page/20.jpg', n: 'files/page/20.jpg', t: 'files/thumb/20.jpg' },
  { l: 'files/page/21.jpg', n: 'files/page/21.jpg', t: 'files/thumb/21.jpg' },
  { l: 'files/page/22.jpg', n: 'files/page/22.jpg', t: 'files/thumb/22.jpg' },
  { l: 'files/page/23.jpg', n: 'files/page/23.jpg', t: 'files/thumb/23.jpg' },
  { l: 'files/page/24.jpg', n: 'files/page/24.jpg', t: 'files/thumb/24.jpg' },
  { l: 'files/page/25.jpg', n: 'files/page/25.jpg', t: 'files/thumb/25.jpg' },
  { l: 'files/page/26.jpg', n: 'files/page/26.jpg', t: 'files/thumb/26.jpg' },
  { l: 'files/page/27.jpg', n: 'files/page/27.jpg', t: 'files/thumb/27.jpg' },
  { l: 'files/page/28.jpg', n: 'files/page/28.jpg', t: 'files/thumb/28.jpg' },
  { l: 'files/page/29.jpg', n: 'files/page/29.jpg', t: 'files/thumb/29.jpg' },
  { l: 'files/page/30.jpg', n: 'files/page/30.jpg', t: 'files/thumb/30.jpg' },
  { l: 'files/page/31.jpg', n: 'files/page/31.jpg', t: 'files/thumb/31.jpg' },
  { l: 'files/page/32.jpg', n: 'files/page/32.jpg', t: 'files/thumb/32.jpg' },
  { l: 'files/page/33.jpg', n: 'files/page/33.jpg', t: 'files/thumb/33.jpg' },
  { l: 'files/page/34.jpg', n: 'files/page/34.jpg', t: 'files/thumb/34.jpg' },
  { l: 'files/page/35.jpg', n: 'files/page/35.jpg', t: 'files/thumb/35.jpg' },
  { l: 'files/page/36.jpg', n: 'files/page/36.jpg', t: 'files/thumb/36.jpg' },
  { l: 'files/page/37.jpg', n: 'files/page/37.jpg', t: 'files/thumb/37.jpg' },
  { l: 'files/page/38.jpg', n: 'files/page/38.jpg', t: 'files/thumb/38.jpg' },
  { l: 'files/page/39.jpg', n: 'files/page/39.jpg', t: 'files/thumb/39.jpg' },
  { l: 'files/page/40.jpg', n: 'files/page/40.jpg', t: 'files/thumb/40.jpg' },
  { l: 'files/page/41.jpg', n: 'files/page/41.jpg', t: 'files/thumb/41.jpg' },
  { l: 'files/page/42.jpg', n: 'files/page/42.jpg', t: 'files/thumb/42.jpg' },
  { l: 'files/page/43.jpg', n: 'files/page/43.jpg', t: 'files/thumb/43.jpg' },
  { l: 'files/page/44.jpg', n: 'files/page/44.jpg', t: 'files/thumb/44.jpg' },
  { l: 'files/page/45.jpg', n: 'files/page/45.jpg', t: 'files/thumb/45.jpg' },
  { l: 'files/page/46.jpg', n: 'files/page/46.jpg', t: 'files/thumb/46.jpg' },
  { l: 'files/page/47.jpg', n: 'files/page/47.jpg', t: 'files/thumb/47.jpg' },
  { l: 'files/page/48.jpg', n: 'files/page/48.jpg', t: 'files/thumb/48.jpg' },
  { l: 'files/page/49.jpg', n: 'files/page/49.jpg', t: 'files/thumb/49.jpg' },
  { l: 'files/page/50.jpg', n: 'files/page/50.jpg', t: 'files/thumb/50.jpg' },
  { l: 'files/page/51.jpg', n: 'files/page/51.jpg', t: 'files/thumb/51.jpg' },
  { l: 'files/page/52.jpg', n: 'files/page/52.jpg', t: 'files/thumb/52.jpg' },
  { l: 'files/page/53.jpg', n: 'files/page/53.jpg', t: 'files/thumb/53.jpg' },
  { l: 'files/page/54.jpg', n: 'files/page/54.jpg', t: 'files/thumb/54.jpg' },
  { l: 'files/page/55.jpg', n: 'files/page/55.jpg', t: 'files/thumb/55.jpg' },
  { l: 'files/page/56.jpg', n: 'files/page/56.jpg', t: 'files/thumb/56.jpg' },
  { l: 'files/page/57.jpg', n: 'files/page/57.jpg', t: 'files/thumb/57.jpg' },
  { l: 'files/page/58.jpg', n: 'files/page/58.jpg', t: 'files/thumb/58.jpg' },
  { l: 'files/page/59.jpg', n: 'files/page/59.jpg', t: 'files/thumb/59.jpg' },
  { l: 'files/page/60.jpg', n: 'files/page/60.jpg', t: 'files/thumb/60.jpg' },
  { l: 'files/page/61.jpg', n: 'files/page/61.jpg', t: 'files/thumb/61.jpg' },
  { l: 'files/page/62.jpg', n: 'files/page/62.jpg', t: 'files/thumb/62.jpg' },
  { l: 'files/page/63.jpg', n: 'files/page/63.jpg', t: 'files/thumb/63.jpg' },
  { l: 'files/page/64.jpg', n: 'files/page/64.jpg', t: 'files/thumb/64.jpg' },
  { l: 'files/page/65.jpg', n: 'files/page/65.jpg', t: 'files/thumb/65.jpg' },
  { l: 'files/page/66.jpg', n: 'files/page/66.jpg', t: 'files/thumb/66.jpg' },
  { l: 'files/page/67.jpg', n: 'files/page/67.jpg', t: 'files/thumb/67.jpg' },
  { l: 'files/page/68.jpg', n: 'files/page/68.jpg', t: 'files/thumb/68.jpg' },
  { l: 'files/page/69.jpg', n: 'files/page/69.jpg', t: 'files/thumb/69.jpg' },
  { l: 'files/page/70.jpg', n: 'files/page/70.jpg', t: 'files/thumb/70.jpg' },
  { l: 'files/page/71.jpg', n: 'files/page/71.jpg', t: 'files/thumb/71.jpg' },
  { l: 'files/page/72.jpg', n: 'files/page/72.jpg', t: 'files/thumb/72.jpg' },
  { l: 'files/page/73.jpg', n: 'files/page/73.jpg', t: 'files/thumb/73.jpg' },
  { l: 'files/page/74.jpg', n: 'files/page/74.jpg', t: 'files/thumb/74.jpg' },
  { l: 'files/page/75.jpg', n: 'files/page/75.jpg', t: 'files/thumb/75.jpg' },
  { l: 'files/page/76.jpg', n: 'files/page/76.jpg', t: 'files/thumb/76.jpg' },
  { l: 'files/page/77.jpg', n: 'files/page/77.jpg', t: 'files/thumb/77.jpg' },
  { l: 'files/page/78.jpg', n: 'files/page/78.jpg', t: 'files/thumb/78.jpg' },
  { l: 'files/page/79.jpg', n: 'files/page/79.jpg', t: 'files/thumb/79.jpg' },
  { l: 'files/page/80.jpg', n: 'files/page/80.jpg', t: 'files/thumb/80.jpg' },
  { l: 'files/page/81.jpg', n: 'files/page/81.jpg', t: 'files/thumb/81.jpg' },
  { l: 'files/page/82.jpg', n: 'files/page/82.jpg', t: 'files/thumb/82.jpg' },
  { l: 'files/page/83.jpg', n: 'files/page/83.jpg', t: 'files/thumb/83.jpg' },
  { l: 'files/page/84.jpg', n: 'files/page/84.jpg', t: 'files/thumb/84.jpg' },
  { l: 'files/page/85.jpg', n: 'files/page/85.jpg', t: 'files/thumb/85.jpg' },
  { l: 'files/page/86.jpg', n: 'files/page/86.jpg', t: 'files/thumb/86.jpg' },
  { l: 'files/page/87.jpg', n: 'files/page/87.jpg', t: 'files/thumb/87.jpg' },
  { l: 'files/page/88.jpg', n: 'files/page/88.jpg', t: 'files/thumb/88.jpg' },
  { l: 'files/page/89.jpg', n: 'files/page/89.jpg', t: 'files/thumb/89.jpg' },
  { l: 'files/page/90.jpg', n: 'files/page/90.jpg', t: 'files/thumb/90.jpg' },
  { l: 'files/page/91.jpg', n: 'files/page/91.jpg', t: 'files/thumb/91.jpg' },
  { l: 'files/page/92.jpg', n: 'files/page/92.jpg', t: 'files/thumb/92.jpg' },
  { l: 'files/page/93.jpg', n: 'files/page/93.jpg', t: 'files/thumb/93.jpg' },
  { l: 'files/page/94.jpg', n: 'files/page/94.jpg', t: 'files/thumb/94.jpg' },
  { l: 'files/page/95.jpg', n: 'files/page/95.jpg', t: 'files/thumb/95.jpg' },
  { l: 'files/page/96.jpg', n: 'files/page/96.jpg', t: 'files/thumb/96.jpg' },
  { l: 'files/page/97.jpg', n: 'files/page/97.jpg', t: 'files/thumb/97.jpg' },
  { l: 'files/page/98.jpg', n: 'files/page/98.jpg', t: 'files/thumb/98.jpg' },
  { l: 'files/page/99.jpg', n: 'files/page/99.jpg', t: 'files/thumb/99.jpg' },
  {
    l: 'files/page/100.jpg',
    n: 'files/page/100.jpg',
    t: 'files/thumb/100.jpg',
  },
]
var language = [
  {
    language: 'chinese',
    btnFirstPage: '第一页',
    btnNextPage: '下一页',
    btnLastPage: '最后一页',
    btnPrePage: '前一页',
    btnGoToHome: '首页',
    btnDownload: '下载',
    btnSoundOn: '开启声音',
    btnSoundOff: '关闭声音',
    btnPrint: '打印',
    btnThumb: '缩略图',
    btnBookMark: '书签',
    frmBookMark: '书签',
    btnZoomIn: '放大',
    btnZoomOut: '缩小',
    btnAutoFlip: '自动翻页',
    btnStopAutoFlip: '停止自动翻页',
    btnSocialShare: '分享',
    frmSharePanelTitle: '分享',
    frmPanelTitle: '分享到',
    frmShareQRcode: '二维码',
    btnHelp: '帮助',
    btnAbout: '关于',
    btnSearch: '查找',
    btnFullscreen: '全屏',
    btnExitFullscreen: '退出全屏',
    btnMore: '更多',
    frmPrintCaption: '打印',
    frmPrintall: '打印全部',
    frmPrintcurrent: '打印当前页',
    frmPrintRange: '打印页码范围',
    frmPrintexample: '例子: 2,3,5-10',
    frmPrintbtn: '打印',
    frmShareCaption: '分享',
    frmShareLabel: '分享',
    frmShareInfo: '您可以在此发布轻松分享到社交网络.只要点击以下按钮',
    frminsertLabel: '内嵌到网站',
    frminsertInfo: '使用下面的代码来本出版物嵌入到你的网站',
    frmaboutcaption: '联系',
    frmaboutcontactinformation: '联系人信息',
    frmaboutADDRESS: '地址',
    frmaboutEMAIL: '邮件地址',
    frmaboutWEBSITE: '网站',
    frmaboutMOBILE: '手机',
    frmaboutAUTHOR: '作者',
    frmaboutDESCRIPTION: '描述',
    frmSearch: '搜索',
    frmToc: '目录',
    btnTableOfContent: '显示目录',
    btnNote: '注解',
    lblLast: '这是最后一页。',
    lblFirst: '这是第一页。',
    lblFullscreen: '点击查看全屏',
    lblName: '名称',
    lblPassword: '密码',
    lblLogin: '登录',
    lblCancel: '取消',
    lblNoName: '用户名称不能为空。',
    lblNoPassword: '密码不能为空。',
    lblNoCorrectLogin: '请输入正确的用户名和密码。',
    btnVideo: '视频画廊',
    btnSlideShow: '幻灯片放映',
    pnlSearchInputInvalid: '搜索文本太短。',
    btnDragToMove: '鼠标拖动',
    btnPositionToMove: '鼠标移动',
    lblHelp1: '拖动书页页角翻页。',
    lblHelp2: '双击书页放大、缩小。',
    lblCopy: '复制',
    lblAddToPage: '添加到页面',
    lblPage: '页',
    lblTitle: '标题',
    lblEdit: '编辑',
    lblDelete: '删除',
    lblRemoveAll: '删除所有',
    tltCursor: '光标',
    tltAddHighlight: '添加高亮',
    tltAddTexts: '添加文本',
    tltAddShapes: '添加形状',
    tltAddNotes: '添加注释',
    tltAddImageFile: '添加图像文件',
    tltAddSignature: '添加签名',
    tltAddLine: '添加直线',
    tltAddArrow: '添加箭头',
    tltAddRect: '添加矩形',
    tltAddEllipse: '添加椭圆',
    lblDoubleClickToZoomIn: '双击进行放大。',
    lblPages: '页面',
    infCopyToClipboard: '您的浏览器不支持剪贴板，请自己复制。',
    lblDescription: '标题',
    frmLinkLabel: '链接',
    infNotSupportHtml5:
      '您当前的网络浏览器不支持HTML5，请使用最新版本的网络浏览器阅读本书。 我们在这里建议您使用Chrome阅读它。',
    frmHowToUse: '如何使用',
    lblHelpPage1: '移动手指来翻动书页。',
    lblHelpPage2: '使用手势或者双击页面来放大页面。',
    lblHelpPage3: '点击标志到达公司的官方网站。',
    lblHelpPage4: '添加书签、搜索内容、自动翻页。',
    lblHelpPage5: '在移动设备上切换水平和垂直视图。',
    frmQrcodeCaption: '用手机扫描底部的二维码。',
    btnPageBack: '后退',
    btnPageForward: '前进',
    btnLanguage: '切换语言',
    msgConfigMissing: '配置文件丢失，无法打开书籍。',
    btnPhoneNumber: '联系电话',
    frmTelephone: '联系电话',
    btnDialing: '呼叫',
    lblSelectMessage: '请在文本框中复制文本内容。',
    btnSelectText: '选择文字',
    DownloadCurrentPage: '包含当前页面',
    restorePage: '您想恢复以前的会话吗？',
    lblSave: '保存',
    btnDownloadPosterPrompt: '点击下载海报',
    infLongPressToSavePoster: '移动端长按保存海报',
    infLongPressToIndentify: '长按识别二维码',
    infScanCodeToView: '手机扫码阅读',
    lblConfirm: '确认',
    infDeleteNote: '您要删除这条注释吗？',
    btnBack: '后退',
    proFullScreenWarn: '当前的浏览器不支持全屏，请使用Chrome以获得最佳效果。',
    closeFlipSound: '关闭翻页声音',
    closeBackgroundSound: '关闭背景声音',
    btnSettings: '设置',
    tmpl_Flipsoundon: '打开翻页声音',
    tmpl_Backgoundsoundon: '打开背景音乐',
    tmpl_Flipsoundoff: '关闭翻页声音',
    tmpl_Backgoundsoundoff: '关闭背景声音',
    frmVideoListTitle: '视频列表',
    frmVideoTitle: '视频',
    btnMagnifierIn: '打开放大镜',
    btnMagnifierOut: '关闭放大镜',
  },
]
var ols = []
var bmtConfig = { tabs: [], onSideEdge: true }
var staticAd = {
  haveAd: false,
  adPosition: 0,
  adHeight: 60,
  interval: 3000,
  data: [],
}
var videoList = []
var slideshow = []
var flipByAudio = { audioType: 0, audioFile: '', showPlayer: false, items: [] }
var phoneNumber = []
var shareObj = null
var bookPlugin = null
